AssertionError("thermo_feasible")
ErrorException("SCIP's solving was interrupted, but not by a user-given limit!")
